# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fee4dd846581aa37ef2584ba157a5219"
name = "ai-support"
handle = "ai-support-2"
application_url = "https://appears-solar-treat-morgan.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c4e56a25.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_discounts,read_draft_orders,read_gift_cards,read_inventory,read_locations,read_orders,read_product_listings,read_products,read_shipping,write_products"

[auth]
redirect_urls = [
  "https://appears-solar-treat-morgan.trycloudflare.com/auth/callback",
  "https://appears-solar-treat-morgan.trycloudflare.com/auth/shopify/callback",
  "https://appears-solar-treat-morgan.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
